// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PlantCardController from "./plant_card_controller";
application.register("plant-card", PlantCardController);

import FlipcardController from "./flipcard_controller";
application.register("flipcard", FlipcardController);

import SwiperController from "./swiper_controller";
application.register("swiper", SwiperController);

import SearchController from "./search_controller";
application.register("search", SearchController);
